### ISSUE TITLE
why add means?

### ISSUE THREAD

**Issue by xiexuliunian** [PKUZHOU/MTCNN_TensorRT#18]
![image](https://user-images.githubusercontent.com/24749356/84287327-5b9f2800-ab72-11ea-86eb-17074447acde.png)
in this code,why add mean? not sub?

**Comment by PKUZHOU** [comment]
Where is the location of this code？

**Comment by xiexuliunian** [comment]
![image](https://user-images.githubusercontent.com/24749356/84567573-2c73fb00-adac-11ea-92eb-e6b5a44c3993.png)

**Comment by PKUZHOU** [comment]
It seems to be a mistake...

**Comment by xiexuliunian** [comment]
yeah,but the result seem also not too bad......lol

**Comment by PKUZHOU** [comment]
Deep learning's magic
