### ISSUE TITLE
请问现在这个项目是还没有跑通嘛？只有PNet和RNet

### ISSUE THREAD

**Issue by suyue6** [PKUZHOU/MTCNN_TensorRT#2]
如题，谢谢您提供的代码~

**Comment by PKUZHOU** [comment]
我当时对精度需求比较低，对计算速度要求比较高，所以只用到这两个网络，没实现RNET,  既然还是有人要完整的实现，我可能下个月写一下，也可以自己补充，欢迎Pull request

**Comment by suyue6** [comment]
Ok, thank you very much ! Looking forward to your new project ~
And now, I have a big problem :

start generation TenosrRT runtime model
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 4:13: Message type "ditcaffe.NetParameter" has no field named "input_dim288".
ERROR: CaffeParser: Could not parse deploy file
Segmentation fault

Could you tell me how to solver this problem? Thanks ~

**Comment by PKUZHOU** [comment]
What's your tensorRT and caffe version ? I used tensorRT 3

**Comment by suyue6** [comment]
TensorRT 4.0 on TX1 ,   no caffe environment.

**Comment by PKUZHOU** [comment]
Sorry I misplaced the prototxt,  you can test the newest commit now

**Comment by suyue6** [comment]
So happy ~  
It's successful ! but still have some problem( I use the image 4.jpg to run it ) :

start generation TenosrRT runtime model
ERROR: Tensor outputis already set as output
end generation TensorRT runtime model
time is : 68.411s

what can I do for this ? Thanks !

**Comment by PKUZHOU** [comment]
You can Ignore this error, I use more than one Pnet instance in first stage, so there will be more than one output dataflow, which will be reported as error in TensorRT, but it will not affect the results. Your runtime seems a bit long because it contains initialize time.

**Comment by suyue6** [comment]
Ok! Thanks ~

**Comment by suyue6** [comment]
视频的话可以实现实时检测，但是可能是因为是ONet没有实现，有很多误检的小方框，期待您的完整版~

**Comment by PKUZHOU** [comment]
可以通过调整阈值来减少误检

**Comment by suyue6** [comment]
OK! Thank  you ~
I need the whole project, which has ONet , So Looking forward your complete project ~
could you tell me if you have finished this project ? Thanks ~

**Comment by PKUZHOU** [comment]
最近忙着学业上的事情还没有时间搞这个，可能要等月底才能有时间做个完整的出来。如果你对这个工程很感兴趣的话，你可以加我微信Z751722308, 有什么新的进展我会告诉你
